ALTER TABLE  `llamadas` ADD  `NivelViolencia` TEXT NULL ;

INSERT INTO CAMPOS VALUES 
('1. Bromas hirientes','NivelViolencia',1),
('1. Chantajear','NivelViolencia',1),
('1. Mentir/ Engañar','NivelViolencia',1),
('1. Ignorar/ Ley del hielo','NivelViolencia',1),
('1. Celar','NivelViolencia',1),
('1. Culpabilizar','NivelViolencia',1),
('1. Descalificar','NivelViolencia',1),
('1. Ridiculizar/ Ofender','NivelViolencia',1),
('1. Humillar en público','NivelViolencia',1),
('1. Intimidar/ Amenazar','NivelViolencia',1),
('1. Controlar/ Prohibir','NivelViolencia',1),
('2. Destruir artículos personales','NivelViolencia',1),
('2. Manosear','NivelViolencia',1),
('2. Caricias agresivas','NivelViolencia',1),
('2. Golpear “jugando”','NivelViolencia',1),
('2. Pellizcar/ Arañar','NivelViolencia',1),
('2. Empujar/ Jalonear','NivelViolencia',1),
('2. Cachetear','NivelViolencia',1),
('2. Patear','NivelViolencia',1),
('3. Encerrar/ Aislar','NivelViolencia',1),
('3. Amenazar con objetos o armas','NivelViolencia',1),
('3. Amenazar de muerte','NivelViolencia',1),
('3. Forzar a una relación sexual','NivelViolencia',1),
('3. Abuso sexual','NivelViolencia',1),
('3. Violar','NivelViolencia',1),
('3. Mutilar','NivelViolencia',1),
('3. Asesinar','NivelViolencia',1);